language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
script:
  - mvn clean cobertura:cobertura org.jacoco:jacoco-maven-plugin:prepare-agent
after_success:
  - bash <(curl -s https://codecov.io/bash)
