language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "nurhier"
    token:
      secure: "33a2b32b585e8d4c388b49463222c487267b517d" # encrypted value of your token
script:
  - mvn clean cobertura:cobertura org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=utils-collection
after_success:
  - bash <(curl -s https://codecov.io/bash)
