language: java
sudo: false
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
addons:
  sonarcloud:
    organization: "nurhier"
    token:
      secure: "${SONAR_TOKEN}" # encrypted value of your token
script:
  - mvn clean cobertura:cobertura org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=nurhier_utils-collection
after_success:
  - bash <(curl -s https://codecov.io/bash)
